name: JSON to SRS Converter

on:
  # 每天凌晨 00:00 UTC 运行
  schedule:
    - cron: '0 0 * * *'
  # 手动触发
  workflow_dispatch:
  # 当有推送到 main 分支时也触发
  push:
    branches:
      - main
    paths:
      - 'rules/rules/*.json'

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run converter
      run: python json_to_srs_converter.py
        
    - name: Commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add rules/rules/*.srs
        git commit -m "Auto convert JSON to SRS" || echo "No changes to commit"
        git push
