name: Daily Compile JSON to SRS

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 00:00 运行
  workflow_dispatch:

jobs:
  compile-srs:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Git Credentials
      uses: actions/setup-git@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Test GitHub connection
      run: curl -I https://api.github.com

    - name: Install sing-box (Consider using a package manager or container)
      run: |
        curl -L https://github.com/SagerNet/sing-box/releases/download/v1.10.3/sing-box-1.10.3-linux-amd64.tar.gz -o sing-box.tar.gz
        tar -xvf sing-box.tar.gz
        chmod +x sing-box-1.10.3-linux-amd64/sing-box
        mv sing-box-1.10.3-linux-amd64/sing-box ./sing-box

    - name: Create output directory
      run: |
        mkdir -p rules
        chmod 755 rules

    - name: Compile JSON to SRS
      run: |
        for file in rules/*.json; do
          output_file="rules/$(basename ${file%.json}).srs"
          echo "Compiling $file to $output_file"
          if ! ./sing-box rule-set compile --output "$output_file" "$file"; then
            echo "Error compiling $file: $($?)"
            cat "$file"
            exit 1
          fi
        done

    - name: Add and commit changes
      run: |
        git add rules/*.srs
        if git diff --quiet --exit-code; then
          echo "No changes to commit."
        else
          git commit -m "Update SRS files" || exit 1
        fi

    - name: Push changes
      run: |
        git push origin main || exit 1 # Replace 'main' with your branch name

    - name: Upload compiled SRS files (optional)
      uses: actions/upload-artifact@v4
      with:
        name: srs-files
        path: rules/*.srs

    - name: List generated SRS files
      run: |
        echo "Listing generated SRS files:"
        ls -l rules/*.srs
