name: 测试 Setup Git
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      - name: 设置 Git
        uses: actions/setup-git@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: 打印版本
        run: git --version


- name: Test GitHub API Access
  run: curl -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user
