name: Update Rules

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0:00 运行
  workflow_dispatch:      # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Run conversions
      run: |
        python conversion/json_to_srs.py
        python conversion/clash_to_singbox.py
        
    - name: Check for changes
      id: check_changes
      run: |
        git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT
        
    - name: Commit and push if changed
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add rules/
        git commit -m "Auto update rules $(date +'%Y-%m-%d')"
        git push
